### ISSUE TITLE
Crystal staff not being able to have spells

### ISSUE THREAD

**Issue by 1pinheirinho** [Lothrazar/RootsClassic#111] opened 2024-08-28 19:50 UTC
Minecraft version & Mod Version:1.20.1 both

Single player or Server:single player lan where i am the owner

Describe problem (what you were doing / what happened):I am not being able to put any spells into my crystal staff. I have triple checked with multiple videos and i am doing everything correctly. the error that appears is:Ritual Found, but brazier ingredients are missing or not lit.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Mrbysco** [comment] 2024-09-25 14:09
Could you provide a video of the steps taken? That way it's easier for me to look into since I've never crafted nor used a crystal staff

**Comment by Mrbysco** [comment] 2024-09-26 21:04
Duplicate of #98

**Closed as completed by Mrbysco** 2024-09-26 21:04 UTC
