### ISSUE TITLE
Forge requiered by Roots Classic

### ISSUE THREAD

**Issue by ErythroCraft** [Lothrazar/RootsClassic#108] opened 2024-06-09 06:18 UTC
Minecraft version & Mod Version: 1.20.1

Single player or Server: both

Describe problem (what you were doing / what happened):

Acuale recommended forge Version: 1.20.1 - 47.3.0  

Crash log (if any):

[09Juni2024 08:04:24.175] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: 
Missing or unsupported mandatory dependencies:
Mod ID: 'forge', Requested by: 'rootsclassic', Expected range: '[47,47.1.3]', Actual version: '47.3.0'

I can not downgrade forge, becouse many mod are up to date.

Can you create an update, please?

**Comment by Mrbysco** [comment] 2024-06-09 10:24
Duplicate of #100

**Comment by ErythroCraft** [comment] 2024-06-09 10:36
OK. But will you compile the version?

**Closed as completed** 2024-06-14 22:22 UTC
